version: "3"

services:
  api:
    container_name: back-end
    build: ./
    depends_on:
      - db
    command: npm start
    restart: always
    working_dir: /graphql-boilerplate-mongo
    environment:
      REDIS_HOST: redis
      DB_HOST: mongodb://localhost/local:mongodb://localhost/local
    ports:
      - "4000:4000"
    volumes:
      - ./graphql-boilerplate-mongo
      - /graphql-boilerplate-mongo/node_modules
    links:
      - redis
      - db

  db:
    image: mongo
    ports:
      - "27017:27017"
  redis:
    image: redis
    ports:
      - "6379:6379"
