version: "3"

services:
  api:
    container_name: back-end
    build: ./
    depends_on:
      - redis
      - db
    command: npm start
    restart: always
    working_dir: /graphql-boilerplate-mongo
    environment:
      REDIS_HOST: redis

    ports:
      - "4000:4000"
    volumes:
      - ./server:/graphql-boilerplate-mongo
      - /graphql-boilerplate-mongo/node_modules
    links:
      - redis
      - db

  db: # also this is the server name in the adminer
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    environment:
      ADMINER_PLUGINS: "tables-filter tinymce"
      ADMINER_DESIGN: "price"
  redis:
    image: redis
    ports:
      - "6379:6379"

  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: always
    ports:
      - "8889:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
